### ISSUE TITLE
MiniMap notfound

### ISSUE THREAD

**Issue by LuizHGodoy** [skillman1337/moba-threejs#1]
does not render as expected... minimap not found

**Comment by zedsboyfriend** [comment]
it's because the assets are not included in the repository. if you add all the assets, it will work

**Comment by skillman1337** [comment]
it's because the assets are not included in the repository. if you add all the assets, it will work (map, navmesh, sounds)

**Comment by LuizHGodoy** [comment]
could you by any chance send me the assets somehow?

**Comment by skillman1337** [comment]
https://easyupload.io/uk871t

make sure you git checkout the latest version
